# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bag.proto for package 'bag'

require 'grpc'
require 'bag_pb'

module Bag
  module BagService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bag.BagService'

      rpc :CreateApp, ::Bag::CreateAppRequest, ::Bag::CreateAppResponse
      rpc :CreateInstances, ::Bag::CreateInstancesRequest, ::Bag::CreateInstancesResponse
      rpc :CreateInstance, ::Bag::CreateInstanceRequest, ::Bag::CreateInstanceResponse
      rpc :CreateItem, ::Bag::CreateItemRequest, ::Bag::CreateItemResponse
      rpc :CreateRecipe, ::Bag::CreateRecipeRequest, ::Bag::CreateRecipeResponse
      rpc :CreateAction, ::Bag::CreateActionRequest, ::Bag::CreateActionResponse
      rpc :CreateTrade, ::Bag::CreateTradeRequest, ::Bag::CreateTradeResponse
      rpc :ReadIdentity, ::Bag::ReadIdentityRequest, ::Bag::ReadIdentityResponse
      rpc :ReadInventory, ::Bag::ReadInventoryRequest, ::Bag::ReadInventoryResponse
      rpc :ReadItem, ::Bag::ReadItemRequest, ::Bag::ReadItemResponse
      rpc :ReadItems, ::Bag::ReadItemsRequest, ::Bag::ReadItemsResponse
      rpc :ReadInstance, ::Bag::ReadInstanceRequest, ::Bag::ReadInstanceResponse
      rpc :ReadApp, ::Bag::ReadAppRequest, ::Bag::ReadAppResponse
      rpc :ReadTrade, ::Bag::ReadTradeRequest, ::Bag::ReadTradeResponse
      rpc :ReadRecipes, ::Bag::ReadRecipesRequest, ::Bag::ReadRecipesResponse
      rpc :ReadRecipe, ::Bag::ReadRecipeRequest, ::Bag::ReadRecipeResponse
      rpc :ReadAction, ::Bag::ReadActionRequest, ::Bag::ReadActionResponse
      rpc :UpdateIdentityMetadata, ::Bag::UpdateIdentityMetadataRequest, ::Bag::UpdateIdentityMetadataResponse
      rpc :UpdateInstance, ::Bag::UpdateInstanceRequest, ::Bag::UpdateInstanceResponse
      rpc :UpdateItem, ::Bag::UpdateItemRequest, ::Bag::UpdateItemResponse
      rpc :UpdateApp, ::Bag::UpdateAppRequest, ::Bag::UpdateAppResponse
      rpc :UpdateTrade, ::Bag::UpdateTradeRequest, ::Bag::UpdateTradeResponse
      rpc :UpdateRecipe, ::Bag::UpdateRecipeRequest, ::Bag::UpdateRecipeResponse
      rpc :UpdateAction, ::Bag::UpdateActionRequest, ::Bag::UpdateActionResponse
      rpc :DeleteApp, ::Bag::DeleteAppRequest, ::Bag::DeleteAppResponse
      rpc :DeleteInstance, ::Bag::DeleteInstanceRequest, ::Bag::DeleteInstanceResponse
      rpc :CloseTrade, ::Bag::CloseTradeRequest, ::Bag::CloseTradeResponse
      rpc :VerifyKey, ::Bag::VerifyKeyRequest, ::Bag::VerifyKeyResponse
    end

    Stub = Service.rpc_stub_class
  end
end
